## ===> Arc List

In [2]:
graph_1= [(1,2),(2,4),(4,6),(3,2),(2,5),(3,1),(4,5),(6,5)];

8-element Array{Tuple{Int64,Int64},1}:
 (1,2)
 (2,4)
 (4,6)
 (3,2)
 (2,5)
 (3,1)
 (4,5)
 (6,5)

In [8]:
# Loop over arc list
for arc in graph_1
    print(arc)
end

(1,2)(2,4)(4,6)(3,2)(2,5)(3,1)(4,5)(6,5)

In [7]:
# Get nodes from arc list : STUDENTS
unique(vcat([arc[1] for arc in graph_1],[arc[2] for arc in graph_1]))

6-element Array{Int64,1}:
 1
 2
 4
 3
 6
 5

In [13]:
# Outdegree from arc List
function node_degree_arcList(n)
    indegree=0
    outdegree=0
    degree=0
    for arc in graph_1
        (arc[1]==n) && (outdegree+=1) 
        (arc[2]==n) && (indegree+=1) 
        (arc[1]==n || arc[2]==n) && (degree+=1) #STUDENTS
    end
    indegree,outdegree,degree
end

# call:
node_degree_arcList(4)

(1,2,3)

## ===> Adjacency Matrix

In [2]:
function constructAdjMatFromFile(fname)
    data=readcsv(fname,Int)
    n=maximum(data) 
    M=zeros(Bool,n,n)
    m=size(data,1) # arcs
    for arcIndx=1:m
        i,j=data[arcIndx,:]
        M[i,j]=true
    end
    M
end

adjMat= constructAdjMatFromFile("Lab_1_data.csv")




6×6 Array{Bool,2}:
 false   true  false  false  false  false
 false  false  false   true   true  false
  true   true  false  false  false  false
 false  false  false  false   true   true
 false  false  false  false  false  false
 false  false  false  false   true  false

In [3]:
# Outdegree from Adjacency Matrix
function node_degree_adjMat(n,adjMat) # STUDENTS
    indegree=sum(adjMat[:,n] )
    outdegree=sum(adjMat[n,:])
    degree=indegree+outdegree
    indegree,outdegree,degree
end

node_degree_adjMat(4,adjMat)

(1, 2, 3)

## ===> Adjacency List

In [7]:
function constructAdjListFromFile(fname)
    data=readcsv(fname,Int)
    n=maximum(data) 
    m=size(data,1)
  A=Array(Array{Int},n) 
#     A=Array{Array{Int},n}()
    
    for i=1:n A[i]=[] end # Initialization of adjacency list

    for arcIndx=1:m
        i,j=data[arcIndx,:]
        push!(A[i],j) 
    end
    A
end


adjList= constructAdjListFromFile("Lab_1_data.csv")


Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] Array(::Type{Array{Int64,N} where N}, ::Int64) at ./deprecated.jl:51
 [3] constructAdjListFromFile(::String) at ./In[7]:5
 [4] include_string(::String, ::String) at ./loading.jl:515
 [5] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/sahar/.julia/v0.6/IJulia/src/execute_request.jl:160
 [6] eventloop(::ZMQ.Socket) at /home/sahar/.julia/v0.6/IJulia/src/eventloop.jl:8
 [7] (::IJulia.##11#14)() at ./task.jl:335
while loading In[7], in expression starting on line 18


6-element Array{Array{Int64,N} where N,1}:
 [2]    
 [4, 5] 
 [2, 1] 
 [6, 5] 
 Int64[]
 [5]    

## ===> From Adjlist to Matrix and Vice Versa

In [98]:
function fromMatrixToList(Mat)
    n=size(Mat,1)
    A=Array(Array{Int},n) 
    for i=1:n A[i]=[] end # Initialization of adjacency list
     for i=1:n
        j=find(Mat[i,:])
        A[i]= j
#         for k in j
#             push!(A[i],k) 
#         end
    end
    
    return A
end

fromMatrixToList (generic function with 1 method)

In [99]:
A = fromMatrixToList(adjMat)


Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] Array(::Type{Array{Int64,N} where N}, ::Int64) at ./deprecated.jl:51
 [3] fromMatrixToList(::Array{Bool,2}) at ./In[98]:3
 [4] include_string(::String, ::String) at ./loading.jl:515
 [5] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/sahar/.julia/v0.6/IJulia/src/execute_request.jl:160
 [6] eventloop(::ZMQ.Socket) at /home/sahar/.julia/v0.6/IJulia/src/eventloop.jl:8
 [7] (::IJulia.##11#14)() at ./task.jl:335
while loading In[99], in expression starting on line 1


6-element Array{Array{Int64,N} where N,1}:
 [2]    
 [4, 5] 
 [1, 2] 
 [5, 6] 
 Int64[]
 [5]    

In [69]:
function fromListToMatrix(A)
    n=size(A,1)
    Mat=zeros(Bool,n,n)
    
     for i=1:n
        j=A[i]
        Mat[i,j]=true 
    end
    
    return Mat
end

fromListToMatrix (generic function with 1 method)

In [70]:
M = fromListToMatrix(A)

6×6 Array{Bool,2}:
 false   true  false  false  false  false
 false  false  false   true   true  false
  true   true  false  false  false  false
 false  false  false  false   true   true
 false  false  false  false  false  false
 false  false  false  false   true  false

## ===>Implement isConnected on a pred Array

In [72]:
function isConnected(pred,i,j)
    (pred[i] == j || pred[j]==i) && true
end

isConnected (generic function with 1 method)

In [74]:
pred = [0,1,5,2,4]
isConnected(pred,1,4)


false

## ===> Check if a graph is a tree (neither directed-in or directed-out, directed-in or directed-out)


In [77]:
function checkTree(Mat)
    n = size(Mat,1)
    numArcs = sum(Mat)
    if numArcs == n-1
        return true
    else
        return false
    end
end

checkTree (generic function with 1 method)

In [78]:
checkTree(M)

false

In [79]:
function checkDirectedOut(Mat)
    n = size(Mat,1)
    numArcs = sum(Mat)
    if numArcs == n-1
        for i =1:n #suppose that we are starting from node 1 so its indegree is already zero
            if sum(Mat[:,i] ) >1
                return false
            else
                return true
            end
        end
    else
        return false
    end
end

checkDirectedOut (generic function with 1 method)

In [91]:
M2 = [0 1 1 0
0 0 0 1
0 0 0 0
0 0 0 0]#directed-out tree

4×4 Array{Int64,2}:
 0  1  1  0
 0  0  0  1
 0  0  0  0
 0  0  0  0

In [92]:
checkDirectedOut(M2) #directed-out tree

true

In [93]:
checkDirectedOut(M) #not a tree

false

In [94]:
function checkDirectedIn(Mat)
    n = size(Mat,1)
    numArcs = sum(Mat)
    if numArcs == n-1
        for i =1:n 
            if sum(Mat[i,:] ) >1
                return false
            else
                return true
            end
        end
    else
        return false
    end
end

checkDirectedIn (generic function with 1 method)

In [95]:
M3= [0 0 0 0
    1 0 0 0
    1 0 0 0
    0 1 0 0] #directed-in tree 

4×4 Array{Int64,2}:
 0  0  0  0
 1  0  0  0
 1  0  0  0
 0  1  0  0

In [96]:
checkDirectedIn(M3)#directed-in tree 

true

In [97]:
checkDirectedIn(M2)#directed-out tree 

false